from typing import Any, Mapping, Optional

class IOMixin:
    _last_message: str
    _last_message_err: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def ask(self, question: str, default: Optional[Any]) -> str: ...
    def confirm(
        self, question: str, default: Optional[Any], true_answer_regex: Optional[str]
    ) -> str: ...
    def choice(
        self, question: str, choices: Mapping[Any, Any], default: Optional[Any]
    ) -> str: ...
    def overwrite(self, message: Any, size: Optional[int] = None) -> None: ...
    def overwrite_error(self, message: Any, size: Optional[int] = None) -> None: ...
