#!/usr/bin/env bash

# Insert package addition instructions
echo "  # To add additional packages update package_lists/cran.list or package_lists/bioconductor.list"

# Construct formatted lists
CRANPACKAGES=$(cat cran.list | sed -e "s/^/'/" -e "s/$/',/" | tr "\n" " " | sed -e "s/', $/'/")
echo "  - export CRANPACKAGES=\"$CRANPACKAGES\""
BIOCPACKAGES=$(cat bioconductor.list | sed -e "s/^/'/" -e "s/$/',/" | tr "\n" " " | sed -e "s/', $/'/")
echo "  - export BIOCPACKAGES=\"$BIOCPACKAGES\""

# Insert block footer
echo "  # === AUTOGENERATED R PACKAGES END HERE ==="
