#!/usr/bin/env bash

# Insert package addition instructions
echo "  # To add additional packages update package_lists/requested-<python version>.list"

# Initialise temporary files for list operations
COMBINED_27=$(mktemp)
COMBINED_36=$(mktemp)
COMBINED_37=$(mktemp)
NON_CONDA_27_SORTED=$(mktemp)
NON_CONDA_36_SORTED=$(mktemp)
NON_CONDA_37_SORTED=$(mktemp)
COMMON_REQUESTED=$(mktemp)

# Sort the non-conda lists
sort non-conda-27.list > $NON_CONDA_27_SORTED
sort non-conda-36.list > $NON_CONDA_36_SORTED
sort non-conda-37.list > $NON_CONDA_37_SORTED

# Construct combined lists using:
#   1. include requested packages
#   2. include any packages from the utility list
#   3. remove any packages from the sorted non-conda list which will be installed with pip
cat requested-27.list utility-packages-27.list | sort | uniq | comm -23 - $NON_CONDA_27_SORTED > $COMBINED_27
cat requested-36.list utility-packages-36.list | sort | uniq | comm -23 - $NON_CONDA_36_SORTED > $COMBINED_36
cat requested-37.list utility-packages-37.list | sort | uniq | comm -23 - $NON_CONDA_37_SORTED > $COMBINED_37

# Create a combined list
comm -12 $COMBINED_27 $COMBINED_36 | comm -12 - $COMBINED_37 > $COMMON_REQUESTED

# Construct minimal common and environment specific lists
echo "  - export PYTHON_CONDA_COMMON=\"$(cat $COMMON_REQUESTED | tr '\n' ' ' | xargs)\""
echo "  - export PYTHON27_CONDA_ADDITIONAL=\"$(comm -23 $COMBINED_27 $COMMON_REQUESTED | tr '\n' ' ' | xargs)\""
echo "  - export PYTHON36_CONDA_ADDITIONAL=\"$(comm -23 $COMBINED_36 $COMMON_REQUESTED | tr '\n' ' ' | xargs)\""
echo "  - export PYTHON37_CONDA_ADDITIONAL=\"$(comm -23 $COMBINED_37 $COMMON_REQUESTED | tr '\n' ' ' | xargs)\""

# Use lists to construct appropriate environment variables
echo "  # Consolidate package lists for each Python version"
echo "  - export PYTHON27_CONDA_PACKAGES=\"\$PYTHON_CONDA_COMMON \$PYTHON27_CONDA_ADDITIONAL\""
echo "  - export PYTHON36_CONDA_PACKAGES=\"\$PYTHON_CONDA_COMMON \$PYTHON36_CONDA_ADDITIONAL\""
echo "  - export PYTHON37_CONDA_PACKAGES=\"\$PYTHON_CONDA_COMMON \$PYTHON37_CONDA_ADDITIONAL\""

# Construct packages that must be installed with pip
echo "  # Construct lists of packages only available through pip for each Python version"
echo "  - export PYTHON27_PIP_PACKAGES=\"$(cat $NON_CONDA_27_SORTED | tr '\n' ' ' | xargs)\""
echo "  - export PYTHON36_PIP_PACKAGES=\"$(cat $NON_CONDA_36_SORTED | tr '\n' ' ' | xargs)\""
echo "  - export PYTHON37_PIP_PACKAGES=\"$(cat $NON_CONDA_37_SORTED | tr '\n' ' ' | xargs)\""

# Insert block footer
echo "  # === AUTOGENERATED ANACONDA PACKAGES END HERE ==="

rm $COMBINED_27 $COMBINED_36 $COMBINED_37 $NON_CONDA_27_SORTED $NON_CONDA_36_SORTED $NON_CONDA_37_SORTED $COMMON_REQUESTED

