#cloud-config

apt:
  # Preserves the existing /etc/apt/sources.list
  preserve_sources_list: true

  # Update apt database on first boot (ie run apt-get update)
  update: true

# List of packages to install with apt-get
packages:
  - rsync

write_files:
  - content: |
        [mirror]
        ; The directory where the mirror data will be stored.
        directory = /datadrive

        ; The PyPI server which will be mirrored.
        master = https://pypi.python.org

        ; Whether to stop a sync quickly after an error is found or whether to continue
        ; syncing but not marking the sync as successful. Value should be "true" or
        ; "false".
        stop-on-error = false

        ; Whether or not files that have been deleted on the master should be deleted on the mirror, too.
        delete-packages = true
      path: /etc/bandersnatch.conf
  - content: |
        #! /bin/bash
        rsync -rtlzv --delete cran.r-project.org::CRAN /datadrive
      path: /update_mirror.sh


runcmd:
  # Upgrade installation then clean up
  - echo "*** Upgrade and clean up apt-get packages... ***"
  - apt-get -y upgrade
  - apt-get clean

  # Set up disk
  - echo "*** Setting up local disk... ***"
  - (echo n; echo 1; echo ; echo ; echo ; echo w; echo Y) | gdisk /dev/sdc
  - mkfs -t ext4 /dev/sdc1
  - mkdir /datadrive && mount /dev/sdc1 /datadrive
  - UUID=$(blkid | grep "/dev/sdc1" | cut -d'"' -f2)
  - sed "s|UUID|UUID=$UUID\t/datadrive\text4\tdefaults,nofail\t1\t2\nUUID|" /etc/fstab > fstab.tmp
  - mv fstab.tmp /etc/fstab

  # Update the mirror
  - source /update_mirror.sh
