#cloud-config

apt:
  # Preserves the existing /etc/apt/sources.list
  preserve_sources_list: true

  # Update apt database on first boot (ie run apt-get update)
  update: true

# List of packages to install with apt-get
packages:
  - openssh-server
  - python3-pip
  - python3-venv


runcmd:
  # Set up disk
  - echo "*** Setting up local disk... ***"
  - (echo n; echo 1; echo ; echo ; echo ; echo w; echo Y) | gdisk /dev/sdc
  - mkfs -t ext4 /dev/sdc1
  - mkdir /datadrive && mount /dev/sdc1 /datadrive
  - UUID=$(blkid | grep "/dev/sdc1" | cut -d'"' -f2)
  - sed "s|UUID|UUID=$UUID\t/datadrive\text4\tdefaults,nofail\t1\t2\nUUID|" /etc/fstab > fstab.tmp
  - mv fstab.tmp /etc/fstab
  - chown -R adminpypi /datadrive

  # Install pypiserver with pip
  - echo "*** Installing pypiserver... ***"
  - python3 -m venv pypiserver
  - pypiserver/bin/pip install pypiserver

  # Set up pypiserver
  - echo "*** Setting up pypiserver pointing to local disk... ***"
  - /pypiserver/bin/pypi-server -p 8080 -P . -a . /datadrive/web/packages &