#cloud-config

apt:
  # Preserves the existing /etc/apt/sources.list
  preserve_sources_list: true

  # Update apt database on first boot (ie run apt-get update)
  update: true

# List of packages to install with apt-get
packages:
  - openssh-server
  - rsync
  - apache2

users:
  - name: mirrordaemon
    sudo: False

write_files:
  - path: /000-default.conf
    content: |
      <VirtualHost *:80>
        DocumentRoot "/datadrive/"
        <Directory "/datadrive">
            Options Indexes FollowSymLinks Includes ExecCGI
            AllowOverride All
            Order allow,deny
            Allow from all
            Require all granted
        </Directory>
      </VirtualHost>

runcmd:
  # Upgrade installation, clean up, then install nginx
  - echo "*** Upgrade and clean up apt-get packages... ***"
  - apt-get -y upgrade
  - apt-get clean

  # Set up disk
  - echo "*** Setting up local disk... ***"
  - (echo n; echo 1; echo ; echo ; echo ; echo w; echo Y) | gdisk /dev/sdc
  - mkfs -t ext4 /dev/sdc1
  - mkdir /datadrive && mount /dev/sdc1 /datadrive
  - UUID=$(blkid | grep "/dev/sdc1" | cut -d'"' -f2)
  - sed "s|UUID|UUID=$UUID\t/datadrive\text4\tdefaults,nofail\t1\t2\nUUID|" /etc/fstab > fstab.tmp
  - mv fstab.tmp /etc/fstab
  - chown -R mirrordaemon /datadrive

  # Add authorized public key
  - ls /var/lib/waagent/
  - KEYNAME=$(find /var/lib/waagent/ -name "*.prv" | cut -c -57 | cut -d'/' -f5)
  - echo "Found secret named $KEYNAME"
  - cd
  - cp /var/lib/waagent/${KEYNAME}.crt /var/lib/waagent/${KEYNAME}.prv .
  - "openssl pkcs12 -export -passout pass: -in ${KEYNAME}.crt -inkey ${KEYNAME}.prv -out sshkey.pfx"
  - "openssl pkcs12 -passin pass: -in sshkey.pfx -out sshkey.pem -nocerts -nodes"
  - ssh-keygen -f sshkey.pem -y > sshkey.pub
  - mkdir ~mirrordaemon/.ssh
  - cp sshkey.pub ~mirrordaemon/.ssh/authorized_keys
  - chown -R mirrordaemon ~mirrordaemon
  - chgrp -R mirrordaemon ~mirrordaemon
  - chmod 0644 ~mirrordaemon/.ssh/authorized_keys
  - rm -f ${KEYNAME}.* sshkey.*

  # Set up apache
  - echo "*** Setting up apache server pointing to local disk... ***"
  - sed -i "s|/var/www/html|/datadrive|" /etc/apache2/sites-enabled/000-default.conf
  - mv /000-default.conf /etc/apache2/sites-enabled/000-default.conf
  - service apache2 reload