# Generated by Django 2.1 on 2018-10-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_by_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='projects', to='data.Dataset'),
        ),
    ]
