# Generated by Django 2.1 on 2018-11-02 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_auto_20181024_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('referee', 'Referee'), ('investigator', 'Investigator'), ('researcher', 'Researcher')], help_text="The participant's role on this project", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the user was added to the project')),
                ('created_by', models.ForeignKey(help_text='User who added this user to the project', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'project')},
        ),
    ]
