# Generated by Django 2.1 on 2018-11-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_participant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('referee', 'Referee'), ('research_coordinator', 'Research Coordinator'), ('investigator', 'Investigator'), ('researcher', 'Researcher')], help_text="The participant's role on this project", max_length=50),
        ),
    ]
