---
extends: default
rules:
  # Remove requirement for comments to start with '# ' as this breaks cloud-init
  comments:
    require-starting-space: false
  # Remove requirement to start with '---' as this breaks cloud-init
  document-start: disable
  # Allow longer lines
  line-length:
    max: 400
