############################  Display  #############################

# Verbose program output
# Accepts log level: "error", "warn", "info", "debug", "trace"
verbose = "warn"

# Output format
format = "detailed"

# Output display mode
mode = "emoji"

# Don't show interactive progress bar while checking links.
no_progress = false

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "2d"

# A list of status codes that will be ignored from the cache
cache_exclude_status = "500.."

#############################  Runtime  #############################

# File to read and write cookies
# cookie_jar = "cookie-jar"

# Number of threads to utilize.
# Defaults to number of cores available to the system if omitted.
# threads = 2

# Maximum number of allowed redirects.
max_redirects = 10

# Maximum number of allowed retries before a link is declared dead.
max_retries = 2

# Maximum number of concurrent link checks.
max_concurrency = 14

# extension applied to files without extension
default_extension = "html"

# Resolve directories to index files
index_files = ["index.html"]

#############################  Requests  ############################

# User agent to send with each request.
user_agent = "curl/7.83. 1"

# Website timeout from connect to response finished.
timeout = 20

# Minimum wait time in seconds between retries of failed requests.
retry_wait_time = 2

# Comma-separated list of accepted status codes for valid links.
accept = ["200", "202", "429"]

# Proceed for server connections considered insecure (invalid TLS).
insecure = false

# When links are available using HTTPS, treat HTTP links as errors.
require_https = true

# Request method
method = "get"

# Fallback extensions to apply when a URL does not specify one.
# This is common in documentation tools that cross-reference files without extensions.
fallback_extensions = ["md", "html"]

# Enable the checking of fragments in links.
include_fragments = false

#############################  Exclusions  ##########################

# Skip missing input files (default is to error if they don't exist).
skip_missing = false

# Check links inside `<code>` and `<pre>` blocks as well as Markdown code
# blocks.
include_verbatim = false

# Exclude URLs and mail addresses from checking. The values are treated as regular expressions
exclude = [
  'code\.visualstudio\.com', # 403
  'doi\.org',                # 403
  'entra.microsoft\.com',    # Requires authentication (403)
  'example\.org',            # domain used for examples only
  'github\.com',             # Requires authentication (403)
  'hedgedoc\.org',           # 403
  'ipaddressguide\.com',     # 403
  'opensource\.org',         # 403
  'portal\.azure\.com',      # 403
  'turing\.ac\.uk',          # DDOS protection
]

# Exclude paths from getting checked. The values are treated as regular expressions
exclude_path = [
  'docs/build/html/_static/webpack-macros.html',
  'docs/build/html/contributing/index.html',
]

# Check the specified file extensions
# extensions = ["md", "html"]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = false

# Exclude private IP address ranges from checking.
exclude_private = false

# Exclude link-local IP address range from checking.
exclude_link_local = false

# Exclude loopback IP address range and localhost from checking.
exclude_loopback = false

# Check mail addresses
include_mail = true

# Check WikiLinks in Markdown files
include_wikilinks = false

#############################  Other  #############################

# Use the Wayback Machine as web archive
archive = "wayback"

# Search and suggest link replacements for all broken links
suggest = true
