# Generated by Django 2.1 on 2018-10-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_add_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('data_provider_representative', 'Data Provider Representative'), ('research_coordinator', 'Research Coordinator'), ('referee', 'Referee'), ('investigator', 'Investigator'), ('researcher', 'Researcher')], max_length=50),
        ),
    ]
