# Generated by Django 2.1 on 2018-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20181010_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('data_provider_representative', 'Data Provider Representative'), ('research_coordinator', 'Research Coordinator'), ('referee', 'Referee'), ('investigator', 'Investigator'), ('researcher', 'Researcher')], help_text="The participant's role on this project", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('system_controller', 'System Controller'), ('research_coordinator', 'Research Coordinator')], help_text="The user's role in the system", max_length=50),
        ),
    ]
