# Generated by Django 2.1 on 2018-11-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_update_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time the user was added to the project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='created_by',
            field=models.ForeignKey(help_text='User who added this user to the project', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
