# Generated by Django 2.1 on 2018-11-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_user_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='project',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
