# Generated by Django 2.1 on 2018-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_make_email_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
