from typing import Any, Dict, Optional, OrderedDict

class DotMap(OrderedDict[Any, Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, k: Any) -> Any: ...
    def __getitem__(self, k: Any) -> Any: ...
    def __setattr__(self, k: Any, v: Any) -> None: ...
    def __setitem__(self, k: Any, v: Any) -> None: ...
    def toDict(self, seen: Optional[Dict[str, Any]] = ...) -> Dict[str, Any]: ...
