---

# SSH server settings
ssh_allow_users: "{{ dsvm_admin_user }}"
ssh_server_match_address:
  - address: "{{ guacamole_private_ip }}"
    rules:
      - AllowUsers *
      - DenyUsers "{{ dsvm_admin_user }}"
      - PasswordAuthentication yes
      - AuthenticationMethods password

# Packages
apt_packages_development:
  - git
  - julia
  - octave
  - gfortran
  - build-essential
  - jupyter
  - r-base

apt_packages_editors:
  - vim
  - emacs

apt_packages_latex:
  - texlive-full
  - texstudio
