---

# SSH server settings
ssh_challengeresponseauthentication: yes
ssh_server_match_address:
  - address: "{{ guacamole_private_ip }}"
    rules:
      - PasswordAuthentication yes
      - AuthenticationMethods password
      - DenyUsers guacamole_admin

# Packages
apt_packages_development:
  - git
  - julia
  - octave
  - gfortran
  - build-essential
  - jupyter
  - r-base

apt_packages_editors:
  - vim
  - emacs

apt_packages_latex:
  - texlive-full
  - texstudio
