---

# Fail2ban settings
# Ignore attempts from guacamole VM to prevent locking users out
fail2ban_ignoreips:
  - "{{ guacamole_private_ip }}"

# SSH server settings
ssh_allow_users: "{{ dsvm_admin_user }}"
ssh_server_match_address:
  - address: "{{ guacamole_private_ip }}"
    rules:
      - AllowUsers *
      - DenyUsers "{{ dsvm_admin_user }}"
      - PasswordAuthentication yes
      - AuthenticationMethods password

# Packages
apt_packages_development:
  - git
  - julia
  - octave
  - gfortran
  - build-essential
  - jupyter
  - r-base

apt_packages_shells:
  - bash
  - zsh
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - fish

apt_packages_editors:
  - vim
  - emacs

apt_packages_latex:
  - texlive-full
  - texstudio

apt_packages: "{{ apt_packages_development | union(apt_packages_shells) | union(apt_packages_editors) | union(apt_packages_latex) }}"
