---

# SSH client settings
ssh_client_password_login: yes

# Pip packages
pip_install_packages:
  - docker
  - docker-compose

# Docker users
docker_users:
  - "{{ ansible_user }}"

# Docker compose variables
guacamole_home_container: /guacamole_home
guacamole_home_host: "{{ ansible_user_dir }}/guacamole_home"
guacamole_extensions_dir: "{{ guacamole_home_host }}/extensions"
guac_db_name: guacamole
guac_db_user: guacamole
guac_db_password:
guac_version: "1.3.0"
postgres_version: "13.1"
init_db_file: "{{ ansible_user_dir }}/initdb.sql"
postgres_volume: "{{ ansible_user_dir }}/postgres"
traefik_version: "v2.3"
traefik_acme_volume: "{{ ansible_user_dir }}/acme"

# Guacamole webapp variables
guac_admin_user: guacadmin
guac_admin_password:
dsvm_connection_identifier: 1
dsvm_connection_params:
  name: dsvm
  parentIdentifier: ROOT
  protocol: rdp
  parameters:
    hostname: "{{ dsvm_private_ip }}"
    port: "3389"
    security: Any
    ignore-cert: "true"
    server-layout: en-gb-qwerty
    timezone: Etc/GMT+0
  attributes:
    max-connections:
    max-connections-per-user:
    weight:
    failover-only:
    guacd-port:
    guacd-encryption:
    guacd-hostname:
