#cloud-config
package_upgrade: true

packages:
  - xfce4
  - xfce4-terminal
  - xrdp

write_files:
  - path: "/startwm.sh"
    content: |
      #!/bin/sh
      if [ -r /etc/default/locale ]; then
        . /etc/default/locale
        export LANG LANGUAGE
      fi
      # Start xfce4
      startxfce4

runcmd:
  # Disable light-locker which can cause irritating error messages
  - echo "Hidden=true" >> /etc/xdg/autostart/light-locker.desktop
  # Set default session to xfce4
  - mv /startwm.sh /etc/xrdp/startwm.sh
  - chmod 0755 /etc/xrdp/startwm.sh
  - echo xfce4-session > ~USERNAME/.xsession
  # Ensure that user owns their directory and has a sensible PATH
  - chown -R USERNAME ~USERNAME
  - echo "export PATH=$PATH:/anaconda/bin/:/opt/anaconda3/bin:/opt/julia/julia-1.0.1/bin:/dsvm/tools/torch/bin:/opt/torch/install/bin:/opt/azurestorage/:/opt/spark/spark-2.4.0-bin-hadoop2.7/bin" >> /etc/profile
  - cp /etc/profile ~USERNAME/.bashrc
  # Restart xrdp to reflect changes made above
  - service xrdp restart

