#cloud-config

apt:
  # Preserves the existing /etc/apt/sources.list
  preserve_sources_list: true

  # Update apt database on first boot (ie run apt-get update)
  update: true

# List of packages to install with apt-get
packages:
  - openssh-server
  - rsync
  - apache2

# Add the mirrordaemon user
users:
  - name: mirrordaemon
    sudo: False

# Authorise the SSH key for the external CRAN mirror
ssh_authorized_keys:
  - EXTERNAL_SSH_KEY_PLACEHOLDER

write_files:
  - path: /000-default.conf
    content: |
      <VirtualHost *:80>
        DocumentRoot "/datadrive/"
        <Directory "/datadrive">
            Options Indexes FollowSymLinks Includes ExecCGI
            AllowOverride All
            Order allow,deny
            Allow from all
            Require all granted
        </Directory>
      </VirtualHost>

runcmd:
  # Upgrade installation, clean up, then install nginx
  - echo "*** Upgrade and clean up apt-get packages... ***"
  - apt-get -y upgrade
  - apt-get clean

  # Set up disk
  - echo "*** Setting up local disk... ***"
  - (echo n; echo 1; echo ; echo ; echo ; echo w; echo Y) | gdisk /dev/sdc
  - mkfs -t ext4 /dev/sdc1
  - mkdir /datadrive && mount /dev/sdc1 /datadrive
  - UUID=$(blkid | grep "/dev/sdc1" | cut -d'"' -f2)
  - sed "s|UUID|UUID=$UUID\t/datadrive\text4\tdefaults,nofail\t1\t2\nUUID|" /etc/fstab > fstab.tmp
  - mv fstab.tmp /etc/fstab
  - chown -R mirrordaemon /datadrive

  # Set up apache
  - echo "*** Setting up apache server pointing to local disk... ***"
  - sed -i "s|/var/www/html|/datadrive|" /etc/apache2/sites-enabled/000-default.conf
  - mv /000-default.conf /etc/apache2/sites-enabled/000-default.conf
  - service apache2 reload