from typing import List, Optional

from cleo.io import ConsoleIO

from .base_command import BaseCommand

class Command(BaseCommand):
    def __init__(self) -> None: ...
    def handle(self) -> Optional[int]: ...
    def io(self) -> ConsoleIO: ...
    def option(self, key: Optional[str]) -> bool | str | List[str] | None: ...
