from _typeshed import Incomplete

class DictMixin:
    def __setitem__(self, key, item) -> None: ...
    def __getitem__(self, key): ...
    def __len__(self) -> int: ...
    def __delitem__(self, key) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def has_key(self, k): ...
    def update(self, *args, **kwargs): ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def get(self, key, default: Incomplete | None = ...): ...
