from typing import Optional

from clikit.api.formatter import Formatter

from .input import Input
from .output import Output

class IO(Formatter):
    def __init__(self, input: Input, output: Output, error_output: Output) -> None: ...
    def error_line(self, string: str, flags: Optional[int] = ...) -> None: ...
    def error(self, string: str, flags: Optional[int] = ...) -> None: ...
    def verbosity(self) -> int: ...
    def write_line(self, string: str, flags: Optional[int] = ...) -> None: ...
    def write(self, string: str, flags: Optional[int] = ...) -> None: ...
