#cloud-config
package_upgrade: false

write_files:
  - path: /etc/gitlab/gitlab.rb
    content: |
      external_url 'http://gitlab-ce.hxakzvpf0otezeojz3wqhme5wg.cx.internal.cloudapp.net'
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' 
        main: # 'main' is the GitLab 'provider ID' of this LDAP server
          label: 'LDAP'
          host: '<gitlab-rb-host>'
          port: 389
          uid: 'sAMAccountName'
          method: 'plain' # "tls" or "ssl" or "plain"
          bind_dn: 'CN=DSGROUP<gitlab-rb-dsgroup> Gitlab LDAP,OU=Safe Haven Service Accounts,DC=<gitlab-rb-dc1>,DC=<gitlab-rb-dc2>,DC=<gitlab-rb-dc3>'
          password: '<gitlab-rb-pw>'
          active_directory: true
          allow_username_or_email_login: true
          block_auto_created_users: false
          base: 'OU=Safe Haven Research Users,DC=<gitlab-rb-dc1>,DC=<gitlab-rb-dc2>,DC=<gitlab-rb-dc3>'
          user_filter: '(&(objectClass=user)(memberOf=CN=SG DSGROUP<gitlab-rb-dsgroup> Research Users,OU=Safe Haven Security Groups,DC=<gitlab-rb-dc1>,DC=<gitlab-rb-dc2>,DC=<gitlab-rb-dc3>))' 
      attributes:
        username: ['uid', 'userid', 'sAMAccountName']
        email:    ['mail', 'email', 'userPrincipalName']
        name:       'cn'
        first_name: 'givenName'
        last_name:  'sn'
      EOS
      git_data_dirs({ "default" => { "path" => "/media/gitdata" } })          
  
runcmd:
  - echo "script running"
  - touch /root/running
  - echo "10.250.66.153 gitlab-testing gitlab.dsgroup9.co.uk" >> /etc/hosts
  - echo "Europe/London" > /etc/timezone    
  - dpkg-reconfigure -f noninteractive tzdata
  - (echo o; echo n; echo p; echo 1; echo  ; echo  ; echo w) | fdisk /dev/sdc
  - mkfs.ext4 /dev/sdc1 -L DataDrive
  - cp /etc/fstab /etc/fstab.$(date +%Y-%m-%d)
  - echo "UUID=$(blkid -s UUID -o value /dev/sdc1) /media/gitdata ext4 defaults 0 2" >> /etc/fstab
  - mkdir /media/gitdata
  - mount -a


