#cloud-config
package_upgrade: false

runcmd:
  - echo "<hackmd-ip> <hackmd-hostname> <hackmd-fqdn>" >> /etc/hosts
  - echo "Europe/London" > /etc/timezone
  - dpkg-reconfigure -f noninteractive tzdata
  - apt-get update
  - apt upgrade
  - apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable"
  - apt update
  - apt install -y docker-ce
  - apt install -y docker-compose
  - git clone https://github.com/hackmdio/docker-hackmd.git /src/docker-hackmd
  - sed -i "s/version: '3'/version: '2'/" /src/docker-hackmd/docker-compose.yml
  - export ENVLOC=$(($(grep -n environment /src/docker-hackmd/docker-compose.yml | tail -1 | cut -d : -f 1)+1))
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_ALLOW_ANONYMOUS=false" /src/docker-hackmd/docker-compose.yml
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_ALLOW_FREEURL=true" /src/docker-hackmd/docker-compose.yml
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_EMAIL=false" /src/docker-hackmd/docker-compose.yml
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_USERCDN=false" /src/docker-hackmd/docker-compose.yml
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_LDAP_SEARCHFILTER=<hack-md-user-filter>" /src/docker-hackmd/docker-compose.yml
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_LDAP_SEARCHBASE=<hackmd-ldap-base>" /src/docker-hackmd/docker-compose.yml
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_LDAP_BINDCREDETIALS=<hackmd-bind-creds>" /src/docker-hackmd/docker-compose.yml
    - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_LDAP_BINDDN=<hackmd-bind-dn>" /src/docker-hackmd/docker-compose.yml
  - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_LDAP_URL=<hackmd-ldap-url>" /src/docker-hackmd/docker-compose.yml
    - sed -i "$ENVLOC i\ \ \ \ \ \ \ \ - HMD_LDAP_PROVIDERNAME=<hackmd-ldap-bios>" /src/docker-hackmd/docker-compose.yml
    - docker-compose -f /src/docker-hackmd/docker-compose.yml up -d
  
