#cloud-config
package_upgrade: false

write_files:
  - path: /etc/gitlab/gitlab.rb
    content: |
      external_url 'http://<gitlab-ip>'
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' 
        main: # 'main' is the GitLab 'provider ID' of this LDAP server
          label: 'LDAP'
          host: '<gitlab-rb-host>'
          port: 389
          uid: 'sAMAccountName'
          method: 'plain' # "tls" or "ssl" or "plain"
          bind_dn: '<gitlab-rb-bind-dn>'
          password: '<gitlab-rb-pw>'
          active_directory: true
          allow_username_or_email_login: true
          block_auto_created_users: false
          base: '<gitlab-rb-base>'
          user_filter: '<gitlab-rb-user-filter>'
      attributes:
        username: ['uid', 'userid', 'sAMAccountName']
        email:    ['mail', 'email', 'userPrincipalName']
        name:       'cn'
        first_name: 'givenName'
        last_name:  'sn'
      EOS
      git_data_dirs({ "default" => { "path" => "/data/gitdata" } })    
  
runcmd:
  # Install LDAP tools for debugging LDAP issues
  - apt-get install ldap-utils
  # Configure server
  - echo "Configuring server"
  - echo "<gitlab-ip> <gitlab-hostname> <gitlab-fqdn>" >> /etc/hosts
  - echo "Europe/London" > /etc/timezone    
  - dpkg-reconfigure -f noninteractive tzdata
  - echo "*** Setting up data disk... ***"
  - parted /dev/sdc mklabel gpt
  - parted /dev/sdc mkpart primary ext4 0% 100%
  - parted /dev/sdc print
  - sleep 5
  - mkfs -t ext4 /dev/sdc1
  - mkdir -p /datadrive
  - mount /dev/sdc1 /datadrive
  - UUID=$(blkid | grep "/dev/sdc1" | cut -d'"' -f2)
  - sed "s|UUID|UUID=$UUID\t/datadrive\text4\tdefaults,nofail\t1\t2\nUUID|" /etc/fstab > fstab.tmp
  - mv fstab.tmp /etc/fstab
  - mkdir -p /data/gitlab-data
  # Configure Gitlab
  - echo "Configuring Gitlab"
  # Set root password and don't prompt for it to be reset when web app first loaded
  - |
    echo "user = User.find_by(username: 'root');user.password=user.password_confirmation='<gitlab-root-password>';user.password_automatically_set=false;user.save!;exit;" | gitlab-rails console production
  # Turn off user account creation
  - |
    gitlab-rails runner "ApplicationSetting.last.update_attributes(signup_enabled: false)"
    # Reload Gitlab configuration and restart Gitlab
  - gitlab-ctl reconfigure
  
    # Restrict login to SHM domain (must be done AFTER Gitlab update)
  - |
    gitlab-rails runner "ApplicationSetting.last.update_attributes(domain_whitelist: ['<gitlab-login-domain>'])"
    # Reload Gitlab configuration and restart Gitlab
  - gitlab-ctl reconfigure
  - echo "Gitlab configured"
