package_upgrade: false

#write_files:
runcmd:
  - echo "<DSG-Subnet-Data-Prefix>.151 gitlab gitlab.dsgroup<dsg-id>.co.uk" >> /etc/hosts
  - echo "Europe/London" > /etc/timezone    
  - dpkg-reconfigure -f noninteractive tzdata
  - (echo o; echo n; echo p; echo 1; echo  ; echo  ; echo w) | fdisk /dev/sdc
  - mkfs.ext4 /dev/sdc1 -L DataDrive
  - cp /etc/fstab /etc/fstab.$(date +%Y-%m-%d)
  - echo "UUID=$(blkid -s UUID -o value /dev/sdc1) /media/gitdata ext4 defaults 0 2" >> /etc/fstab
  - mkdir /media/gitdata
  - mount -a
  - sed -i "$(grep -nr 'ldap_enabled' /etc/gitlab/gitlab.rb | cut -d : -f 1) ,$(grep -nr 'last_name: ' /etc/gitlab/gitlab.rb | head -1 | cut -d : -f 1) s/^#*//" /etc/gitlab/gitlab.rb
  - sed -i "$(($(grep -nr 'sync_ssh_keys' /etc/gitlab/gitlab.rb | tail -1 | cut -d : -f 1)+1)), $(($(grep -nr 'sync_ssh_keys' /etc/gitlab/gitlab.rb | tail -1 | cut -d : -f 1)+1))  s/^#* //" /etc/gitlab/gitlab.rb
