#cloud-config
package_upgrade: false

write_files:
  - path: /etc/gitlab/gitlab.rb
    content: |
      external_url 'http://gitlab-ce.hxakzvpf0otezeojz3wqhme5wg.cx.internal.cloudapp.net'
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' 
        main: # 'main' is the GitLab 'provider ID' of this LDAP server
          label: 'LDAP'
          host: '<gitlab-rb-host>'
          port: 389
          uid: 'sAMAccountName'
          method: 'plain' # "tls" or "ssl" or "plain"
          bind_dn: '<gitlab-rb-bind-dn>'
          password: '<gitlab-rb-pw>'
          active_directory: true
          allow_username_or_email_login: true
          block_auto_created_users: false
          base: '<gitlab-rb-base>'
          user_filter: '<gitlab-rb-user-filter>'
      attributes:
        username: ['uid', 'userid', 'sAMAccountName']
        email:    ['mail', 'email', 'userPrincipalName']
        name:       'cn'
        first_name: 'givenName'
        last_name:  'sn'
      EOS
      git_data_dirs({ "default" => { "path" => "/media/gitdata" } })          
  
runcmd:
  - echo "Gitlab cloud-init script running"
  - echo "<gitlab-ip> <gitlab-hostname> <gitlab-fqdn>" >> /etc/hosts
  - echo "Europe/London" > /etc/timezone    
  - dpkg-reconfigure -f noninteractive tzdata
  - parted /dev/sdc mkpart primary ext4 0% 100%
  - mkfs.ext4 /dev/sdc1 -L DataDrive
  - cp /etc/fstab /etc/fstab.$(date +%Y-%m-%d)
  - echo "UUID=$(blkid -s UUID -o value /dev/sdc1) /media/gitdata ext4 defaults 0 2" >> /etc/fstab
  - mkdir /media/gitdata
  - mount -a
