version: '3.7'
networks:
    network_default:
services:
    cocalc:
        container_name: cocalc_cocalc_compose
        image: sagemathinc/cocalc:{{sre.webapps.cocalc.dockerVersion}}
        networks:
            - network_default
        ports:
            - 443:443
        volumes:
            - /data/cocalc:/projects
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/pip.conf:/etc/pip.conf:ro
            - /etc/R/Rprofile.site:/etc/R/Rprofile.site:ro
            - /ingress:/data:ro
        restart: always
