# Note that the environment variables are not all documented, but can be found in https://github.com/apache/guacamole-client/blob/1.3.0/guacamole-docker/bin/start.sh
#
# We are not currently using the LDAP settings, but they are left here in case we move MFA into a separate app and switch back to LDAP authentication
# https://enterprise.glyptodon.com/doc/latest/storing-connection-data-within-ldap-950383.html has a good write-up of how to control access using group membership
#
# Originally based on boschkundendienst/guacamole-docker-compose
version: '3.7'
networks:
    network_private:
    network_public:
services:
    postgres:
        container_name: postgres_guacamole_compose
        image: postgres:12.2
        networks:
            - network_private
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /opt/postgresql/data:/var/lib/postgresql/data:rw
            - /opt/postgresql/scripts:/scripts:ro
        environment:
            PGDATA: /var/lib/postgresql/data/guacamole
            POSTGRES_DB: guacamole
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: {{postgres-password}}
        restart: always

    guacd:
        container_name: guacd_guacamole_compose
        image: guacamole/guacd:1.3.0
        networks:
            - network_private
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            GUACD_LOG_LEVEL: debug
        restart: always

    guacamole:
        container_name: guacamole_guacamole_compose
        image: guacamole/guacamole:1.3.0
        depends_on:
            - guacd
            - postgres
        networks:
            - network_private
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            GUACD_HOSTNAME: guacd
            LOGBACK_LEVEL: debug
            #LDAP_HOSTNAME: {{ldap-hostname}}
            #LDAP_PORT: {{ldap-port}}
            #LDAP_USER_BASE_DN: {{ldap-user-base-dn}}
            #LDAP_USERNAME_ATTRIBUTE: sAMAccountName
            #LDAP_GROUP_BASE_DN: {{ldap-group-base-dn}}
            #LDAP_SEARCH_BIND_DN: {{ldap-search-user-dn}}
            #LDAP_SEARCH_BIND_PASSWORD: {{ldap-search-user-password}}
            POSTGRES_HOSTNAME: postgres
            POSTGRES_DATABASE: guacamole
            POSTGRES_USER: guacamole
            POSTGRES_PASSWORD: {{postgres-password}}
            OPENID_AUTHORIZATION_ENDPOINT: https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/authorize
            OPENID_JWKS_ENDPOINT: https://login.microsoftonline.com/{{tenant_id}}/discovery/v2.0/keys
            OPENID_ISSUER: https://login.microsoftonline.com/{{tenant_id}}/v2.0
            OPENID_USERNAME_CLAIM_TYPE: email
            OPENID_CLIENT_ID: {{application_id}}
            OPENID_REDIRECT_URI: https://{{sre_fqdn}}
        restart: always

    nginx:
        container_name: nginx_guacamole_compose
        image: nginx
        links:
            - guacamole
        networks:
            - network_private
            - network_public
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /opt/nginx/guacamole.conf:/etc/nginx/conf.d/guacamole.conf:ro
            - /opt/ssl/conf:/etc/letsencrypt:ro
            - /opt/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
        command: |
            /bin/sh -c "while :; do
                            sleep 6h & wait $${!};
                            nginx -s reload;
                        done &
                        nginx -g 'daemon off;'"
        restart: always
