---
version: "3"
services:
  nexus:
    image: sonatype/nexus3
    expose:
      - 8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /nexus-data:/nexus-data
    restart: always
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/nexus/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - nexus
    restart: always
