---
version: "3"
services:
  nexus:
    container_name: nexus_nexus_compose
    image: sonatype/nexus3:3.65.0
    expose:
      - 8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /nexus-data:/nexus-data
    restart: always
  nginx:
    container_name: nginx_nexus_compose
    image: nginx:1.25
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/nexus/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - nexus
    restart: always
