---

- name: Enable and start auditd service
  ansible.builtin.systemd:
    name: auditd
    enabled: true
    state: started

- name: Get minimum uid  # noqa: inline-env-var
  ansible.builtin.command:
    cmd: awk '/^\s*UID_MIN/{print $2}' /etc/login.defs
  register: uid_min
  changed_when: false

- name: Template auditd rules
  ansible.builtin.template:
    src: etc/audit/rules.d/audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    mode: '0640'
  notify: Restart auditd

- name: Copy auditd privileged executable rules script
  ansible.builtin.copy:
    src: usr/local/bin/privileged-rules
    dest: /usr/local/bin/privileged-rules
    mode: '0500'

- name: Generate auditd privileged executable rules
  ansible.builtin.shell:
    cmd: /usr/local/bin/privileged-rules > /etc/audit/rules.d/50-privileged.rules
    creates: /etc/audit/rules.d/50-privileged.rules
  notify: Restart auditd
