---

- name: Enable SSH password authentication
  # Should look to migrate to https://github.com/dev-sec/ansible-collection-hardening
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    validate: sshd -T -f %s
  notify: Restart sshd

- name: Enable PAM SSH authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM'
    line: 'UsePAM yes'
    validate: sshd -T -f %s
  notify: Restart sshd
