---

- name: Enable bash autocompletion globally
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    block: |
      # enable bash completion in interactive shells
      if [ ! $(shopt -oq posix) ]; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
            . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
            . /etc/bash_completion
        fi
      fi

- name: Copy bashrc skeleton
  ansible.builtin.copy:
    src: etc/skel/bashrc
    dest: /etc/skel/.bashrc
    mode: '0755'
