[tool.poetry]
name = "Python PYTHON_VERSION"
version = "1.0.0"
description = "Python PYTHON_VERSION"
authors = ["ROOT <root@localhost>"]

[tool.poetry.dependencies]
python = "PYTHON_VERSION"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
