#cloud-config

package_update: true
package_upgrade: true

disk_setup:
  /dev/disk/azure/scsi1/lun0:
    table_type: gpt
    layout: true
    overwrite: true

fs_setup:
  - device: /dev/disk/azure/scsi1/lun0
    filesystem: ext4
    parition: 1

mounts:
  - [/dev/disk/azure/scsi1/lun0-part1, /scratch, ext4, "defaults"]
  - [//<datamount-username>.file.core.windows.net/ingress, /data, cifs, "credentials=/etc/smbcredentials.secret,vers=3.0,dir_mode=0777,file_mode=0777,serverino"]

write_files:
  - path: "/etc/smbcredentials.secret"
    owner: root:root
    permissions: "0600"
    content: |
      username=<datamount-username>
      password=<datamount-password>
