#cloud-config
package_upgrade: false

write_files:
  - path: "/etc/xrdp/startwm.sh"
    owner: root:root
    permissions: "0755"
    content: |
      #!/bin/sh
      if [ -r /etc/default/locale ]; then
        . /etc/default/locale
        export LANG LANGUAGE
      fi
      # Start xfce4
      startxfce4
  - path: "/etc/domain-join.secret"
    owner: root:root
    permissions: "0400"
    content: |
      <domain-join-password>
  - path: "/etc/ldap.secret"
    owner: root:root
    permissions: "0400"
    content: |
      <ldap-search-user-password>
  - path: "/opt/installation/join_domain.sh"
    owner: root:root
    permissions: "0500"
    content: |
      <join_domain.sh>
  - path: "/opt/installation/.smbcredentials"
    owner: root:root
    permissions: "0600"
    content: |
      username=<datamount-username>
      password=<datamount-password>
  - path: "/etc/ldap.conf"
    owner: root:root
    permissions: "0444"
    content: |
      # The distinguished name of the search base.
      base <ou-research-users-path>
      # Restrict users to those in the security group of this SRE
      filter <ldap-sre-user-filter>
      # Specify the LDAP server by URI
      uri ldap://<shm-dc-hostname-upper>.<shm-fqdn-lower>:389
      # The LDAP version to use (defaults to 3 if supported by client library)
      ldap_version 3
      # The distinguished name used to bind to the server
      rootbinddn <ldap-search-user-dn>
      # Do not hash the password: rely on the server to do so (default)
      pam_password md5
  - path: "/etc/krb5.conf"
    owner: root:root
    permissions: "0444"
    content: |
      <krb5.conf>
  - path: "/opt/installation/kerberos_configuration.sh"
    owner: root:root
    permissions: "0500"
    content: |
      # Edit LDAP config
      echo "Checking LDAP config"
      echo ">=== /etc/ldap.conf ===<"
      cat /etc/ldap.conf
      echo ">=== end of /etc/ldap.conf ===<"
      # Edit Kerberos config
      echo "Checking Kerberos config"
      echo ">=== /etc/krb5.conf ===<"
      cat /etc/krb5.conf
      echo ">=== end of /etc/krb5.conf ===<"
  - path: "/opt/installation/user_login_configuration.sh"
    owner: root:root
    permissions: "0500"
    content: |
      # Configure sssd logins
      echo "Configuring sssd..."
      sed -i -E 's|(use_fully_qualified_names = ).*|\1False|' /etc/sssd/sssd.conf
      sed -i -E 's|(fallback_homedir = ).*|\1/home/%u|' /etc/sssd/sssd.conf
      sed -i -E 's|(access_provider = ).*|\1simple|' /etc/sssd/sssd.conf
      echo ">=== /etc/sssd/sssd.conf ===<"
      grep -v "^[#;]" /etc/sssd/sssd.conf | grep -v "^$"
      echo ">=== end of /etc/sssd/sssd.conf ===<"
      # Restart sssd to ensure that these settings get propagated
      systemctl restart sssd
      sleep 10
      systemctl status sssd
      # Edit the pam session configuration file
      echo "Updating PAM configuration..."
      PAM_INFORMATION="session required|pam_mkhomedir.so|skel=/etc/skel/|umask=0022"
      sed "/pam_unix/ a $PAM_INFORMATION" /etc/pam.d/common-session | tr "|" "\t" > /tmp/common-session
      mv /tmp/common-session /etc/pam.d/common-session
      echo ">=== /etc/pam.d/common-session ===<"
      grep -v "^#" /etc/pam.d/common-session | grep -v "^$"
      echo ">=== end of /etc/pam.d/common-session ===<"
  - path: "/opt/installation/setup_disk.sh"
    owner: root:root
    permissions: "0500"
    content: |
      #!/bin/sh
      if [ $# -ne 2 ]; then echo "$(basename $0) requires two arguments!"; fi
      DISK_LUN=$1
      FOLDER_PATH=$2
      # Create folder and grant appropriate access
      echo ">=== Creating new mount at '$FOLDER_PATH'... ===<"
      mkdir -p $FOLDER_PATH
      DISK_PATH="/dev/disk/azure/scsi1/lun${DISK_LUN}"
      DEVICE=$(readlink -f ${DISK_PATH})
      PARTITION="${DEVICE}1"
      echo "Using partition ${PARTITION} from disk ${DISK_PATH}"
      # Get the partition table format of the disk
      PARTITION_TABLE=$(parted $DEVICE print 2> /dev/null | egrep '^Partition Table:' | sed -e 's/Partition Table: //')
      # If the device has no partition table, then create one before partitioning the disk and making an ext4 file system
      if [ "$PARTITION_TABLE" = "unknown" ]; then
          echo "Formatting ${DEVICE}..."
          yes | parted $DEVICE mklabel gpt > /dev/null 2>&1
          parted $DEVICE mkpart primary ext4 0% 100% > /dev/null 2>&1
          sleep 5
          mkfs -t ext4 $PARTITION > /dev/null 2>&1
          parted $DEVICE print
      fi
      # Ensure that there is exactly one fstab entry for the primary partition
      cp /etc/fstab /tmp/fstab
      grep -v "${FOLDER_PATH}" /tmp/fstab > /etc/fstab
      echo "${DISK_PATH}-part1\t${FOLDER_PATH}\text4\tdefaults,nofail\t0\t2" >> /etc/fstab
      rm /tmp/fstab 2> /dev/null
      tail -n 1 /etc/fstab
  - path: "/etc/jaas.conf"
    owner: root:root
    permissions: "0444"
    content: |
      pgjdbc {
      com.sun.security.auth.module.Krb5LoginModule required
          useTicketCache=true
          debug=true
          renewTGT=true
          doNotPrompt=true;
      };
  - path: "/etc/pip.conf"
    owner: root:root
    permissions: "0444"
    content: |
      # Add the PyPI mirror to our global settings
      [global]
      index = <mirror-url-pypi>
      index-url = <mirror-url-pypi>/simple
      trusted-host = <mirror-host-pypi>
  - path: "/etc/R/Rprofile.site"
    owner: root:root
    permissions: "0444"
    content: |
      ## Set Rprofile.site to the appropriate CRAN mirror
      local({
          r <- getOption("repos")
          r["CRAN"] <- "<mirror-url-cran>"
          options(repos = r)
      })
  - path: "/etc/skel/.xsession"
    owner: root:root
    permissions: "0444"
    content: |
      xfce4-session
  - path: "/usr/share/xrdp/xrdp_custom_logo.bmp"
    owner: root:root
    encoding: gz+b64
    permissions: "0644"
    content: |
      <xrdpCustomLogoEncoded>
  - path: "/etc/skel/.config/JetBrains/PYCHARM_VERSION/options/project.default.xml"
    owner: root:root
    permissions: "0400"
    content: |
      <project.default.xml>
  - path: "/etc/skel/.config/JetBrains/PYCHARM_VERSION/options/jdk.table.xml"
    owner: root:root
    permissions: "0400"
    content: |
      <jdk.table.xml>
  - path: "/etc/skel/.bashrc"
    owner: root:root
    permissions: "0644"
    content: |
      # determine if terminal has color support
      case "$TERM" in
          xterm-color|*-256color) color_prompt=yes;;
      esac

      # set prompt
      if [ "$color_prompt" = yes ]; then
          PS1='\[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
      else
          PS1='\u:\W\$ '
      fi
      unset color_prompt

      # enable color support for ls and grep
      if [ -x /usr/bin/dircolors ]; then
          test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
          alias ls='ls --color=auto'
          alias grep='grep --color=auto'
          alias fgrep='fgrep --color=auto'
          alias egrep='egrep --color=auto'
      fi
  - path: "/etc/bash.bashrc"
    owner: root:root
    permissions: "0644"
    append: true
    content: |
      # enable bash completion in interactive shells
      if [ ! $(shopt -oq posix) ]; then
          if [ -f /usr/share/bash-completion/bash_completion ]; then
              . /usr/share/bash-completion/bash_completion
          elif [ -f /etc/bash_completion ]; then
              . /etc/bash_completion
          fi
      fi
  - path: "/etc/clamav/clamd.conf"
    owner: root:root
    permissions: "0644"
    append: true
    content: |
      # Scan on access settings
      # Scan on access for locally mounted disks
      OnAccessIncludePath /home
      OnAccessIncludePath /scratch
      OnAccessIncludePath /mnt
      # Scan on access for samba shares
      OnAccessIncludePath /shared
      OnAccessIncludePath /data
      OnAccessIncludePath /output
      # Prevent access to infected files
      OnAccessPrevention yes
      OnAccessExcludeUname clamav
      OnAccessExcludeRootUID yes
  - path: "/lib/systemd/system/clamav-clamonacc.service"
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Clamav on access scanning daemon
      Requires=clamav-daemon.service
      After=clamav-daemon.service

      [Service]
      Type=simple
      User=root
      ExecStart=/usr/bin/clamonacc --foreground=true
      Restart=on-failure
      RestartSec=30

      [Install]
      WantedBy=multi-user.target
  - path: "/lib/systemd/system/clamav-clamdscan.service"
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Clamav full system scan
      Requires=clamav-daemon.service
      After=clamav-daemon.service

      [Service]
      Type=oneshot
      User=root
      ExecStart=/usr/bin/clamdscan --fdpass --multiscan /
  - path: "/lib/systemd/system/clamav-clamdscan.timer"
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Run clamdscan every week

      [Timer]
      # Will run on every Monday at 00:00:00
      OnCalendar=weekly
      AccuracySec=1h
      # Will run if a job was missed (e.g. due to system being powered down)
      Persistent=true

      [Install]
      WantedBy=timers.target


runcmd:
  - echo ">=== Beginning DSVM configuration... ===<"
  # Join this VM to the domain and allow domain users to log in
  - /opt/installation/kerberos_configuration.sh
  - /opt/installation/join_domain.sh "<shm-fqdn-lower>" "<ou-linux-servers-path>" "<domain-join-username>" "<vm-hostname>" "<vm-ipaddress>"
  - /opt/installation/user_login_configuration.sh
  # Set locale
  - locale-gen en_GB.UTF-8
  - update-locale LANG=en_GB.UTF-8
  # PyCharm configuration
  - PY27_VERSION=$(/opt/anaconda/envs/py27/bin/python --version 2>&1 | cut -d ' ' -f2)
  - PY36_VERSION=$(/opt/anaconda/envs/py36/bin/python --version 2>&1 | cut -d ' ' -f2)
  - PY37_VERSION=$(/opt/anaconda/envs/py37/bin/python --version 2>&1 | cut -d ' ' -f2)
  - sed -i "s/PY27_VERSION/$PY27_VERSION/g" /etc/skel/.config/JetBrains/PYCHARM_VERSION/options/jdk.table.xml
  - sed -i "s/PY36_VERSION/$PY36_VERSION/g" /etc/skel/.config/JetBrains/PYCHARM_VERSION/options/jdk.table.xml
  - sed -i "s/PY37_VERSION/$PY37_VERSION/g" /etc/skel/.config/JetBrains/PYCHARM_VERSION/options/jdk.table.xml
  - PYCHARM_VERSION=$(grep "dataDirectoryName" /snap/pycharm-community/current/product-info.json | cut -d':' -f2 | xargs | sed "s/,//")
  - mv /etc/skel/.config/JetBrains/PYCHARM_VERSION /etc/skel/.config/JetBrains/${PYCHARM_VERSION}
  # TODO remove this
  - echo "-Djava.security.auth.login.config=/etc/jaas.conf" >> /usr/share/dbeaver/dbeaver.ini
  # Set default keyboard to a generic 105 key en-GB
  - sed -i 's|XKBMODEL=.*|XKBMODEL=\"pc105\"|g' /etc/default/keyboard
  - sed -i 's|XKBLAYOUT=.*|XKBLAYOUT=\"gb\"|g' /etc/default/keyboard
  - grep -v "^[# ]" /etc/default/keyboard
  # Disable light-locker which can cause irritating error messages
  - echo "Disabling screen lock..."
  - echo "Hidden=true" >> /etc/xdg/autostart/light-locker.desktop
  # Set default terminal and panel for xfce
  - echo "Setting xfce default terminal and panel..."
  - sed -i -E 's/(TerminalEmulator=).*/\1xfce4-terminal/' /etc/xdg/xfce4/helpers.rc
  - cp /etc/xdg/xfce4/panel/default.xml /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
  # Set xrdp defaults
  - echo "Setting xrdp defaults..."
  # Change colours
  - sed -i "s|dark_grey=808080|dark_grey=ffffff|g" /etc/xrdp/xrdp.ini                       # title bar (unselected)
  - sed -i "s|blue=009cb5|blue=ffffff|g" /etc/xrdp/xrdp.ini                                 # title bar (selected)
  - sed -i "s|ls_top_window_bg_color=.*|ls_top_window_bg_color=000000|g" /etc/xrdp/xrdp.ini # teal background
  - sed -i "s|ls_bg_color=.*|ls_bg_color=ffffff|g" /etc/xrdp/xrdp.ini                       # grey box
  # Change window title
  - sed -i "s|.*ls_title=.*|ls_title=\.|g" /etc/xrdp/xrdp.ini
  # Change logo
  - sed -i "s|ls_logo_filename=.*|ls_logo_filename=/usr/share/xrdp/xrdp_custom_logo.bmp|g" /etc/xrdp/xrdp.ini
  # Centre buttons
  - sed -i "s|ls_btn_ok_x_pos=.*|ls_btn_ok_x_pos=85|g" /etc/xrdp/xrdp.ini
  - sed -i "s|ls_btn_cancel_x_pos=.*|ls_btn_cancel_x_pos=180|g" /etc/xrdp/xrdp.ini
  # Remove all sessions except Xorg
  - sed -i '/\[X11rdp\]/,/^$/d' /etc/xrdp/xrdp.ini           # delete lines from [X11rdp] until next empty line
  - sed -i '/\[Xvnc\]/,/^$/d' /etc/xrdp/xrdp.ini             # delete lines from [Xvnc] until next empty line
  - sed -i '/\[console\]/,/^$/d' /etc/xrdp/xrdp.ini          # delete lines from [console] until next empty line
  - sed -i '/\[vnc-any\]/,/^$/d' /etc/xrdp/xrdp.ini          # delete lines from [vnc-any] until next empty line
  - sed -i '/\[sesman-any\]/,/^$/d' /etc/xrdp/xrdp.ini       # delete lines from [sesman-any] until next empty line
  - sed -i '/\[neutrinordp-any\]/,/^$/d' /etc/xrdp/xrdp.ini  # delete lines from [neutrinordp-any] until next empty line
  # Ensure that xrdp is running and enabled at startup
  - echo ">=== Restart xrdp service... ===<"
  - systemctl enable xrdp
  - systemctl enable xrdp-sesman
  - systemctl restart xrdp
  - sleep 10
  - systemctl status xrdp
  # Mount ingress data folder with read-only local access [remote access is controlled by SMB rules]
  - echo ">=== Mount data folder using SMB... ===<"
  - mkdir -p /data
  - echo "//<dataserver-hostname>/Ingress\t/data\tcifs\tcredentials=/opt/installation/.smbcredentials\t0\t0" >> /etc/fstab
  - tail -n 1 /etc/fstab
  - mount /data
  # Mount shared folder with full local access [remote access is controlled by SMB rules]
  - echo ">=== Mount output folder using SMB... ===<"
  - mkdir -p /shared
  - echo "//<dataserver-hostname>/Shared\t/shared\tcifs\tcredentials=/opt/installation/.smbcredentials,file_mode=0777,dir_mode=0777\t0\t0" >> /etc/fstab
  - tail -n 1 /etc/fstab
  - mount /shared
  # Mount egress data folder with full local access [remote access is controlled by SMB rules]
  - echo ">=== Mount output folder using SMB... ===<"
  - mkdir -p /output
  - echo "//<dataserver-hostname>/Egress\t/output\tcifs\tcredentials=/opt/installation/.smbcredentials,file_mode=0777,dir_mode=0777\t0\t0" >> /etc/fstab
  - tail -n 1 /etc/fstab
  - mount /output
  # Configure disks
  - echo ">=== Mount and configure disks... ===<"
  # This matches the order of disk in Add_DSVM.ps1 which is passed to a loop in Deployments.psm1
  - /opt/installation/setup_disk.sh 1 /home
  - /opt/installation/setup_disk.sh 2 /scratch
  - echo ">=== Enabling clamav services... ===<"
  # Allow unlimited recursion when scanning
  - sed -i 's/^MaxDirectoryRecursion .*/MaxDirectoryRecursion 0/' /etc/clamav/clamd.conf
  # Enable clamav-daemon
  - systemctl enable clamav-daemon
  - systemctl status clamav-daemon
  # Enable clamav scan on access
  - systemctl enable clamav-clamonacc
  - systemctl status clamav-clamonacc
  # Enable clamv periodic scan
  - systemctl enable clamav-clamdscan.timer
  - systemctl status clamav-clamdscan.timer


# Shutdown so that we can tell when the job has finished by polling the VM state
power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: True
