#cloud-config

write_files:
  - path: "/opt/pg-ldap-sync/configuration.yaml"
    permissions: "0700"
    content: |
      {{guacamole_pg_ldap_sync.yaml}}

  - path: "/opt/guacamole/docker-compose.yml"
    permissions: "0400"
    content: |
      {{guacamole_docker_compose.yml}}

  - path: "/opt/nginx/nginx.conf"
    permissions: "0400"
    content: |
      {{guacamole_nginx_nginx.conf}}

  - path: "/opt/nginx/guacamole.conf"
    permissions: "0400"
    content: |
      {{guacamole_nginx_guacamole.conf}}

  - path: "/opt/postgresql/db_update.sql"
    permissions: "0444"
    content: |
      {{guacamole_db_update.sql}}

  - path: "/opt/postgresql/synchronise_database.sh"
    permissions: "0500"
    content: |
      #! /bin/bash
      pg_ldap_sync -c /opt/pg-ldap-sync/configuration.yaml -vvv
      docker cp /opt/postgresql/db_update.sql $(docker ps --filter "name=postgres" | grep "postgres" | cut -d' ' -f1):/db_update.sql
      docker-compose -f /opt/guacamole/docker-compose.yml exec postgres psql -U guacamole -f /db_update.sql

  - path: "/opt/postgresql/data/connections.csv"
    permissions: "0444"
    content: |
      DSVM Main;{{initial_compute_vm_ip}}

# Set locale and timezone
locale: en_GB.UTF-8
timezone: {{timezone}}

# Set the NTP server
# By default we use Google's NTP servers which are incompatible with other servers due to leap-second smearing
ntp:
  pools:
    - {{ntp-server}}

# Configure apt repositories
apt:
  preserve_sources_list: true
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 # Docker Release (CE deb) <docker@docker.com>

# Install necessary apt packages
packages:
  - docker-ce
  - docker-compose
  - gcc
  - libpq-dev
  - make
  - ruby
  - ruby-dev
package_update: true
package_upgrade: true

runcmd:
  # Suppress apt prompts and warning messages
  - DEBIAN_FRONTEND=noninteractive
  - export DEBIAN_FRONTEND

  # Clean up installation - getting to this point takes approximately 30 mins
  - echo ">=== Cleaning up apt-get packages... ===<"
  - apt-get -y autoremove
  - apt-get clean

  # Ensure that Docker is running
  - echo "Current Docker status..."
  - systemctl start docker
  - systemctl enable docker
  - systemctl status docker

  - echo ">=== Creating dummy SSL certificates... ===<"
  - mkdir -p /opt/certbot/conf/live/{{sre_fqdn}} /opt/certbot/www
  - openssl rand -out /root/.rnd -hex 256
  - openssl req -nodes -newkey rsa:2048 -new -x509 -days 1 -keyout /opt/certbot/conf/live/{{sre_fqdn}}/privkey.pem -out /opt/certbot/conf/live/{{sre_fqdn}}/fullchain.pem -subj '/CN=localhost'
  - docker-compose -f /opt/guacamole/docker-compose.yml up --force-recreate -d nginx # start nginx using the dummy certificates
  - ls -alh /opt/certbot/conf/live/{{sre_fqdn}}

  # Get initial Let's Encrypt certificates
  - echo ">=== Replacing dummy SSL certificates..."
  - docker-compose -f /opt/guacamole/docker-compose.yml run --rm --entrypoint "rm -rf /etc/letsencrypt/live/{{sre_fqdn}} && rm -rf /etc/letsencrypt/archive/{{sre_fqdn}} && rm -rf /etc/letsencrypt/renewal/{{sre_fqdn}}.conf" certbot # remove the old certificates
  - docker-compose -f /opt/guacamole/docker-compose.yml run --rm --entrypoint "certbot certonly --webroot -w /var/www/certbot --register-unsafely-without-email --rsa-key-size 2048 --agree-tos --force-renewal -d {{sre_fqdn}} -d {{sre_fqdn}}" certbot # generate new certificates
  - ls -alh /opt/certbot/conf/live/{{sre_fqdn}}

  # Setup Guacamole
  - echo ">=== Starting Docker compose services... ===<"
  - docker-compose -f /opt/guacamole/docker-compose.yml down
  - docker-compose -f /opt/guacamole/docker-compose.yml up -d
  - sleep 30
  # Generate the necessary SQL config for the local PostgreSQL database and run it
  - docker-compose -f /opt/guacamole/docker-compose.yml exec guacamole /opt/guacamole/bin/initdb.sh --postgres > /opt/postgresql/db_init.sql
  - echo "CREATE ROLE ldap_users;" >> /opt/postgresql/db_init.sql
  - echo "CREATE ROLE ldap_groups;" >> /opt/postgresql/db_init.sql
  - docker cp /opt/postgresql/db_init.sql $(docker ps --filter "name=postgres" | grep "postgres" | cut -d' ' -f1):/db_init.sql
  - docker-compose -f /opt/guacamole/docker-compose.yml exec postgres psql -U guacamole -f /db_init.sql

  # Add LDAP users with pg-ldap-sync and schedule a cronjob
  - echo ">=== Adding LDAP users with pg-ldap-sync... ===<"
  - gem install pg-ldap-sync
  # Run the initial update and schedule a sync every 5 minutes
  - /opt/postgresql/synchronise_database.sh
  - echo ">=== Scheduling database sync every 5 minutes... ===<"
  - echo "*/5 * * * * root /opt/postgresql/synchronise_database.sh" >> /etc/crontab
  - tail -n 1 /etc/crontab


# Shutdown so that we can tell when the job has finished by polling the VM state
power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: True
