# cloud-config

fqdn: <vm-fqdn>

disk_setup:
  /dev/disk/azure/scsi1/lun1:
    table_type: gpt
    layout: true
    overwrite: true

fs_setup:
  - device: /dev/disk/azure/scsi1/lun1
    filesystem: ext4
    partition: 1

mounts:
  - [/dev/disk/azure/scsi1/lun1-part1, /scratch, ext4, "defaults"]
  - [//<storage-account-data-name>.file.core.windows.net/ingress, /data, cifs, "_netdev,credentials=/installation/ingress-credentials.secret,vers=3.0,dir_mode=0755,file_mode=0744,serverino"]
  - [//<storage-account-data-name>.file.core.windows.net/egress, /output, cifs, "_netdev,credentials=/installation/egress-credentials.secret,vers=3.0,dir_mode=0777,file_mode=0777,serverino"]

write_files:
  - path: "/installation/ingress-credentials.secret"
    owner: root:root
    permissions: "0400"
    content: |
      username=<storage-account-data-ingress-name>
      password=<storage-account-data-ingress-key>
  - path: "/installation/egress-credentials.secret"
    owner: root:root
    permissions: "0400"
    content: |
      username=<storage-account-data-egress-name>
      password=<storage-account-data-egress-key>

# Set locale and timezone
locale: en_GB.UTF-8
timezone: <timezone>

# Set the NTP server
# By default we use Google's NTP servers which are incompatible with other servers due to leap-second smearing
ntp:
  pools:
    - <ntp-server>
