#cloud-config

# Create files
write_files:
  - path: "/etc/audit/rules.d/audit.rules"
    permissions: "0400"
    content: |
      {{audit.rules}}

  - path: "/etc/gitlab/gitlab.rb"
    permissions: "0600"
    content: |
      external_url 'http://{{sre.webapps.gitlab.ip}}'
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
        main: # 'main' is the GitLab 'provider ID' of this LDAP server
          label: 'LDAP'
          host: '{{shm.dc.hostname}}.{{shm.domain.fqdn}}'
          port: 389
          uid: 'sAMAccountName'
          method: 'plain' # "tls" or "ssl" or "plain"
          bind_dn: '{{gitlab.ldapSearchUserDn}}'
          password: '{{gitlab.ldapSearchUserPassword}}'
          active_directory: true
          allow_username_or_email_login: true
          block_auto_created_users: false
          base: '{{shm.domain.ous.researchUsers.path}}'
          user_filter: '{{{gitlab.ldapUserFilter}}}'
      attributes:
        username: ['uid', 'userid', 'sAMAccountName']
        email:    ['mail', 'email', 'userPrincipalName']
        name:       'cn'
        first_name: 'givenName'
        last_name:  'sn'
      EOS
      git_data_dirs({ "default" => { "path" => "/data" } })

# Set locale and timezone
locale: en_GB.UTF-8
timezone: {{sre.time.timezone.linux}}

# Set the NTP server
# By default we use Google's NTP servers which are incompatible with other servers due to leap-second smearing
ntp:
  enabled: true
  pools:
    {{#shm.time.ntp.serverAddresses}}
    - {{.}}
    {{/shm.time.ntp.serverAddresses}}

# Configure apt repositories
apt:
  preserve_sources_list: true
  sources:
    gitlab.list:
      source: "deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu focal main"
      keyid: F6403F6544A38863DAA0B6E03F01618A51312F3F  # GitLab B.V. (package repository signing key) <packages@gitlab.com>

# Install necessary apt packages
packages:
  - apt-transport-https
  - auditd
  - ca-certificates
  - curl
  - gitlab-ce
  - gnupg
  - ldap-utils
  - openssh-server
  - postfix
package_update: true
package_upgrade: true

# We know that exactly one data disk will be attached to this VM and it will be attached as lun1
disk_setup:
  /dev/disk/azure/scsi1/lun1:
    table_type: gpt
    layout: true
    overwrite: true
fs_setup:
  - device: /dev/disk/azure/scsi1/lun1
    partition: 1
    filesystem: ext4
mounts:
  - [/dev/disk/azure/scsi1/lun1-part1, /data, ext4, "defaults,nofail"]

# Set hostname
fqdn: {{sre.webapps.gitlab.fqdn}}
hostname: {{sre.webapps.gitlab.fqdn}}

# Add the SRE admin (default) user
users:
  - default

# Run other commands
runcmd:
  # Suppress apt prompts and warning messages
  - DEBIAN_FRONTEND=noninteractive
  - export DEBIAN_FRONTEND

  # Clean up installation
  - echo ">=== Cleaning up apt-get packages... ===<"
  - apt-get -y autoremove
  - apt-get clean

  # Ensure that auditd is running and enabled at startup
  - echo ">=== Enabling auditd services... ===<"
  - systemctl start auditd
  - systemctl enable auditd

  # Check server settings
  - echo ">=== Hostname ===<"
  - hostnamectl
  - echo ">=== Date/time ===<"
  - timedatectl

  # Enable custom GitLab settings and run an initial configuration
  - echo "Running initial configuration"
  - gitlab-ctl reconfigure

  # Set root password and don't prompt for it to be reset when web app first loaded
  - |
    echo "user = User.find_by(username: 'root');user.password=user.password_confirmation='{{gitlab.rootPassword}}';user.password_automatically_set=false;user.save!;exit;" | gitlab-rails console -e production

  # Turn off user account creation
  - |
    gitlab-rails runner "ApplicationSetting.last.update_attributes(signup_enabled: false)"

  # Restrict login to SHM domain (must be done AFTER GitLab update)
  - |
    gitlab-rails runner "ApplicationSetting.last.update_attributes(domain_allowlist: ['{{shm.domain.fqdn}}'])"
  # Reload GitLab configuration and restart GitLab
  - gitlab-ctl reconfigure
  - gitlab-ctl restart

# Shutdown so that we can tell when the job has finished by polling the VM state
power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: true
