#cloud-config

# Update package database on first boot (ie. run apt-get update)
package_update: true

# Upgrade installed packages on first boot (ie. run apt-get upgrade)
package_upgrade: true


apt:
  # Preserves the existing /etc/apt/sources.list
  preserve_sources_list: true

  # Add repositories
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable"
      keyid: 8D81803C0EBFCD88


write_files:
  - path: "/src/guacamole/guacamole.env"
    content: |
      LDAP_HOSTNAME=$LDAP_HOSTNAME
      LDAP_USER_BASE_DN=$LDAP_USER_BASE_DN
      LDAP_GROUP_BASE_DN=$LDAP_GROUP_BASE_DN
      POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  - path: "/src/guacamole/docker-compose.yml"
    content: |
      version: '3.7'
      services:
          postgres:
              image: postgres:12.2
              env_file: guacamole.env
              environment:
                  POSTGRES_DB: guacamole
                  POSTGRES_USER: guacamole

          guacd:
              image: guacamole/guacd:1.1.0

          guacamole:
              image: guacamole/guacamole:1.1.0
              env_file: guacamole.env
              environment:
                  GUACD_HOSTNAME: guacd
                  POSTGRES_HOSTNAME: postgres
                  POSTGRES_DATABASE: guacamole
                  POSTGRES_USER: guacamole
              ports:
              - "8080:8080"
  - path: "/src/guacamole/dbinit.sql"
    content: |
$DBINIT


packages:
  - docker-ce
  - docker-compose

runcmd:
  # Suppress apt prompts and warning messages
  - DEBIAN_FRONTEND=noninteractive
  - export DEBIAN_FRONTEND

  # Make a temporary directory (cloudinit recomends not using /tmp)
  - mkdir /run/cloudinit

  # Clean up installation - getting to this point takes approximately 30 mins
  - echo ">=== Cleaning up apt-get packages... ===<"
  - apt-get -y autoremove
  - apt-get clean

  - echo "Starting Guacamole"
  - docker-compose -f /src/guacamole/docker-compose.yml up -d
  - docker cp /src/guacamole/dbinit.sql `$(docker-compose ps -q postgres):/dbinit.sql
  - docker-compose exec postgres psql -U guacamole -f /dbinit.sql

final_message:
  "System setup through cloud-init is finished. Configuration took `$UPTIME seconds"
