title: Turing Data Safe Haven Documentation
email: turing-safehaven-administrator@turing.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Turing Data Safe Haven Documentation.
baseurl: /data-safe-haven # the subpath of your site, e.g. /blog
collections:
  how_to_guides:
    output: true
  explanations:
    output: true
  reference:
    output: true
  tutorial:
    output: true
markdown: GFM

# Build settings
# theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jemoji
