title: Turing Data Safe Haven Documentation
email: turing-safehaven-administrator@turing.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Turing Data Safe Haven Documentation.
baseurl: /data-safe-haven # the subpath of your site, e.g. /blog
collections:
  data_provider:
    output: true
  dev_and_admin:
    output: true
  checklists:
    output: true
  user_guides:
    output: true
  general:
    output: true
  principal_investigator:
    output: true
  project_manager:
    output: true
markdown: GFM

# Build settings
# theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jemoji
