#cloud-config

# We know that exactly one data disk will be attached to this VM and we currently start numbering from lun1
disk_setup:
  /dev/disk/azure/scsi1/lun1:
    table_type: gpt
    layout: true
    overwrite: true

fs_setup:
  - device: /dev/disk/azure/scsi1/lun1
    partition: 1
    filesystem: ext4

mounts:
  - [/dev/disk/azure/scsi1/lun1-part1, /datadrive, ext4, "defaults,nofail"]

# Configure apt repositories
apt:
  preserve_sources_list: true

# List of packages to install with apt-get
packages:
  - apache2
  - clamav
  - clamav-base
  - clamav-daemon
  - clamav-freshclam
  - clamav-unofficial-sigs
  - openssh-server
  - rsync
package_update: true
package_upgrade: true

write_files:
  - path: "/etc/apt/apt.conf.d/00proxy"
    permissions: "0444"
    content: |
      Acquire::http::Proxy "http://{{monitoring.updateServers.linux.ip}}:8000";

  - path: /var/local/cran-mirror-apache.conf
    permissions: "0644"
    content: |
      <VirtualHost *:80>
        DocumentRoot "/datadrive/mirrordaemon/www/cran"
        <Directory "/datadrive/mirrordaemon/www/cran">
            Options Indexes FollowSymLinks Includes
            AllowOverride All
            Order allow,deny
            Allow from all
            Require all granted
        </Directory>
      </VirtualHost>

# Add the SHM admin (default) and mirrordaemon users
# lock_passwd: Lock the password to disable password login
users:
  - default
  - name: mirrordaemon
    lock_passwd: true
    sudo: false
    ssh_authorized_keys:
      - {{{perInstance.externalMirrorPublicKey}}}

# Set locale and timezone
locale: en_GB.UTF-8
timezone: {{time.timezone.linux}}

# Set the NTP server
# By default we use Google's NTP servers which are incompatible with other servers due to leap-second smearing
ntp:
  enabled: true
  pools:
    {{#time.ntp.serverAddresses}}
    - {{.}}
    {{/time.ntp.serverAddresses}}

runcmd:
  # Suppress apt prompts and warning messages
  - DEBIAN_FRONTEND=noninteractive
  - export DEBIAN_FRONTEND

  # Clean up installation
  - echo ">=== Cleaning up apt-get packages... ===<"
  - apt update
  - apt-get -y autoremove
  - apt-get clean
  - apt --fix-broken install

  # Show authorised SSH keys
  - echo ">=== Authorised SSH keys... ===<"
  - cat ~mirrordaemon/.ssh/authorized_keys

  # Upgrade installation and clean up
  - echo ">=== Upgrade and clean up apt-get packages... ===<"
  - apt-get -y upgrade
  - apt-get clean

  # Set up disk
  - echo ">=== Setting up local disk... ===<"
  - mkdir -p /datadrive/mirrordaemon/www/cran
  - ls -alh /datadrive

  # Fix permissions so that mirrordaemon owns its files
  - chown -R mirrordaemon:mirrordaemon /datadrive/mirrordaemon

  # Set up apache: 'restart' runs it now; 'enable' adds it to the list of services run on boot
  - echo ">=== Setting up apache server pointing to local disk... ===<"
  - mv /var/local/cran-mirror-apache.conf /etc/apache2/sites-enabled/000-default.conf
  - a2enmod rewrite
  - systemctl enable apache2
  - systemctl restart apache2
  - systemctl status apache2


# Shutdown so that we can tell when the job has finished by polling the VM state
power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: true
