#cloud-config

apt:
  update: true

packages:
  - docker.io
  - docker-compose
  - python3-requests

write_files:
  - path: "/opt/configuration/docker-compose.yaml"
    permissions: "0400"
    content: |
      ---
      version: "3"

      services:
        nexus:
          image: sonatype/nexus3
          ports:
            - 80:8081
          volumes:
            - /nexus-data:/nexus-data
          restart: always
  - path: "/opt/configuration/configure-nexus.py"
    permissions: "0500"
    content: |
      {{configure_nexus.py}}

# Set locale and timezone
locale: en_GB.UTF-8
timezone: {{time.timezone.linux}}

# Set the NTP server
# By default we use Google's NTP servers which are incompatible with other servers due to leap-second smearing
ntp:
  enabled: true
  pools:
    {{#time.ntp.serverAddresses}}
    - {{.}}
    {{/time.ntp.serverAddresses}}

runcmd:
  # Ensure that Docker is running and enabled at startup
  - echo ">=== Configuring Docker... ===<"
  - systemctl enable docker
  - systemctl start docker
  - sleep 1m
  - systemctl status docker
  - docker --version
  - docker-compose --version

  # Create directory for Nexus data that is owned by the correct user inside the Docker container
  - echo ">=== Creating Nexus data directory... ===<"
  - mkdir /nexus-data
  - chown -R 200:200 /nexus-data

  # Set up the Nexus container
  - echo ">=== Creating Nexus container... ===<"
  - docker-compose -f /opt/configuration/docker-compose.yaml up -d

  # Give Nexus some time to initialise
  - echo ">=== Waiting for Nexus to initialise (3 minutes)... ===<"
  - sleep 3m

  # Configure Nexus
  - echo ">=== Configuring Nexus... ===<"
  - python3 /opt/configuration/configure-nexus.py --path /nexus-data --admin_password {{{nexus.adminPassword}}} --tier {{nexus.tier}}

power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: true
