#cloud-config

write_files:
  - path: "/etc/clamav/clamd.conf"
    permissions: "0644"
    append: true
    content: |
      {{clamd.conf}}

  - path: "/etc/systemd/system/clamav-clamonacc.service"
    permissions: "0644"
    content: |
      {{clamav-clamonacc.service}}

  - path: "/etc/systemd/system/clamav-clamdscan.service"
    permissions: "0644"
    content: |
      {{clamav-clamdscan.service}}

  - path: "/etc/systemd/system/clamav-clamdscan.timer"
    permissions: "0644"
    content: |
      {{clamav-clamdscan.timer}}

  - path: "/etc/squid-deb-proxy/mirror-dstdomain.acl.d/20-data-safe-haven"
    content: |
      # Additional mirror domains that are allowed by this cache
      apt.postgresql.org
      dbeaver.io
      developer.download.nvidia.com
      packages.gitlab.com
      packages.microsoft.com
      qgis.org
      ubuntu.qgis.org

# Set locale and timezone
locale: en_GB.UTF-8
timezone: {{time.timezone.linux}}

# Set the NTP server
# By default we use Google's NTP servers which are incompatible with other servers due to leap-second smearing
ntp:
  enabled: true
  pools:
    {{#time.ntp.serverAddresses}}
    - {{.}}
    {{/time.ntp.serverAddresses}}

# Install necessary apt packages
packages:
  - clamav
  - clamav-base
  - clamav-daemon
  - clamav-freshclam
  - clamav-unofficial-sigs
  - squid-deb-proxy
package_update: true
package_upgrade: true

runcmd:
  # Suppress apt prompts and warning messages
  - DEBIAN_FRONTEND=noninteractive
  - export DEBIAN_FRONTEND

  # Clean up installation
  - echo ">=== Cleaning up apt-get packages... ===<"
  - apt update
  - apt-get -y autoremove
  - apt-get clean
  - apt --fix-broken install

  # Remove the unnecessary squid service and prevent it from running
  - service squid stop
  - systemctl disable -f squid
  - update-rc.d -f squid remove

power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: true
