#cloud-config
timezone: Europe/London

apt:
  update: true

disk_setup:
  /dev/disk/azure/scsi1/lun1:
    table_type: gpt
    layout: True
    overwrite: True

fs_setup:
  - device: /dev/disk/azure/scsi1/lun1
    filesystem: ext4
    parition: 1

mounts:
  - [/dev/disk/azure/scsi1/lun1-part1, /datadrive, ext4, "defaults"]

packages:
  - docker.io
  - docker-compose
  - python3-requests

write_files:
  - path: "/docker-compose.yaml"
    content: |
      ---
      version: "3"

      services:
        nexus:
          image: sonatype/nexus3
          ports:
            - 8081:8081
          volumes:
            - /datadrive/nexus-data:/nexus-data
          restart: always
  - path: "/configure-nexus.py"
    content: |
      <configure_nexus.py>

runcmd:
  - mv /docker-compose.yaml /datadrive/docker-compose.yaml
  # Create directory for nexus data with correct ownership
  - echo "Creating Nexus data directory"
  - mkdir /datadrive/nexus-data
  - chown -R 200:200 /datadrive/nexus-data
  - echo "Creating Nexus container"
  - docker-compose -f /datadrive/docker-compose.yaml up -d
  # Give Nexus some time to initialise
  - echo "Waiting for Nexus to initialise (3 minutes)"
  - sleep 3m
  # Configure Nexus
  - echo "Configuring Nexus"
  - python3 /configure-nexus.py --path /datadrive/nexus-data --admin_password <nexus-admin-password> --tier 2

power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: True
