---
name: Build documentation

# Run workflow on pushes to matching branches
on: # yamllint disable-line rule:truthy
  push:
    branches: [develop, latest]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install hatch
        run: pip install virtualenv==20.39.0 hatch==1.16.3
        # Temporary workaround. virtualenv==21.0.0 breaks the GH Action.
      - name: Build documentation
        run: hatch run docs:build

      - name: Upload html output as artifact
        uses: actions/upload-artifact@v6
        with:
          name: docs-html-${{ github.run_id }}
          path: ./docs/build/html/

  check_links:
    name: Check links
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            lychee.toml
          sparse-checkout-cone-mode: false

      - name: Ensure destination folder exists
        run: |
          mkdir -p ./docs/build/html

      - name: Download book html files from artifact
        uses: actions/download-artifact@v7
        with:
          name: docs-html-${{ github.run_id }}
          path: ./docs/build/html/

      - name: Print config
        run: |
          cat ./lychee.toml

      - name: List docs files
        run: |
          ls -l ./docs/build/html/**/*.html

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          lycheeVersion: v0.22.0 # To avoid a bug in 0.21 where no file are found, should be revised as the action is updated
          args: --verbose --no-progress --extensions 'html' './docs/build/html/'
          fail: true # fail on broken links
