---
name: Build documentation

# Run workflow on pushes to matching branches
on:  # yamllint disable-line rule:truthy
  push:
    branches: [develop, latest]

# checkout needs 'contents:read'
# deploy needs 'contents:write'
permissions:
  contents: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          pip install -r docs/build/requirements.txt
      - name: Create common directories
        shell: bash
        run: |
          echo "OUTPUTDIR=$(mktemp -d)" >> $GITHUB_ENV
      - name: Build all configured releases
        shell: bash
        run: |
          python3 ./docs/build/build_all_supported_versions.py -o ${{env.OUTPUTDIR}}
      - name: Install html-proofer
        shell: bash
        run: gem install html-proofer -v 3.19.0
      - name: Run HTML proofer
        shell: bash
        run: |
          # - allow links to "#"
          # - rewrite the base URL
          # - ignore links to:
          #   - the data-safe-haven repo (as it is private)
          #   - the data-classification-app repo (as it is private)
          #   - turing.ac.uk (as it requires a CAPTCHA)
          export LC_CTYPE="C.UTF-8"
          htmlproofer ${{env.OUTPUTDIR}}/develop \
            --allow-hash-href \
            --check-favicon \
            --check-html \
            --check-img-http \
            --enforce-https \
            --file-ignore "/_static/" \
            --http-status-ignore "403,429,503" \
            --url-swap "^\/data-safe-haven:/.." \
            --url-ignore "/github.com\/alan-turing-institute\/data-safe-haven/,/github.com\/alan-turing-institute\/data-classification-app/,/turing.ac.uk\//"
      - name: Deploy documentation to GitHub Pages
        if: ${{ !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@60b5e92fe9331f02fa1cdad4d19ddf875be0361c  # This commit corresponds to tag 4.1.6
        with:
          branch: autodocs                     # The branch the action should deploy to.
          folder: ${{env.OUTPUTDIR}}           # The folder the action should deploy.
          git-config-name: Deployment Bot      # Name of the committer
          git-config-email: deploy@github.com  # Email of the committer
          single-commit: true                  # Only keep one commit on the branch
      - name: Finalise build if running locally
        if: ${{ env.ACT }}
        shell: bash
        run: |
          echo "Deliberately causing job to fail so that container is kept alive..."
          exit 1
