---
name: Documentation

# Run workflow on pushes to matching branches
on:  # yamllint disable-line rule:truthy
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Sphinx build
        run: |
          make html SPHINXOPTS="-W"

  check_links:
    name: Check links
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./docs/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Sphinx build
        # Set warnings to be treated as errors
        run: |
          make html SPHINXOPTS="-W"
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          args: find ./docs/build/html -type f -name '*.html' ! -path './docs/build/html/contributing/index.html' | xargs lychee --config='./.lychee.toml' --no-progress
          fail: true  # fail on broken links
