---
name: Test code

# Run workflow on pushes to matching branches
on:  # yamllint disable-line rule:truthy
  push:
    branches: [develop, latest]
  pull_request:
    branches: [develop, latest]

jobs:
  test_powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install requirements
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          deployment/CheckRequirements.ps1 -InstallMissing -IncludeDev
      - name: Test PowerShell
        shell: pwsh
        run: ./tests/Run_Pester_Tests.ps1

  test_markdown_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install requirements
        shell: bash
        run: npm install -g markdown-link-check
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          args: --config='./.lychee.toml' --no-progress --offline '**/*.md' --exclude-path './docs'
          fail: true  # fail on broken links
